"""Data models for mem0 memory architecture.

This module defines the core data structures used in the mem0 memory system:
- MemoryItem: Individual memories stored in vector DB
- ConversationContext: Session-level context stored in regular DB/Redis
- MemoryOperation: Operations for managing memories (ADD, UPDATE, DELETE, NOOP)
"""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class MemoryItem(BaseModel):
    """Represents a single memory (fact) stored in Vector Database.
    
    Each memory is a single fact, not a long conversation. This allows for
    efficient retrieval and updating of specific information.
    
    Attributes:
        id: Unique identifier (UUID v4)
        text: The content of the memory (used for embedding)
        vector: Embedding vector (in production, this would be generated by embedding model)
        metadata: Additional metadata including user_id, agent_id, timestamps, topic
    """
    
    id: str = Field(..., description="Unique memory identifier (UUID v4)")
    text: str = Field(..., description="Memory content (fact) used for embedding")
    vector: Optional[List[float]] = Field(None, description="Embedding vector")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata: user_id, agent_id, created_at, updated_at, topic, scope"
    )
    
    class Config:
        """Pydantic config."""
        json_schema_extra = {
            "example": {
                "id": "mem-123e4567-e89b-12d3-a456-426614174000",
                "text": "User likes vegetarian pizza but hates onions",
                "vector": [0.12, -0.5, 0.33, ...],
                "metadata": {
                    "user_id": "user_123",
                    "agent_id": "agent_sales",
                    "created_at": "2023-10-27T10:00:00Z",
                    "updated_at": "2023-10-27T10:05:00Z",
                    "topic": "food_preference",
                    "scope": "shared"  # "shared" or "private" for multi-agent
                }
            }
        }


class ConversationContext(BaseModel):
    """Represents conversation-level context stored in regular DB/Redis.
    
    This stores session-level information that doesn't need vector search:
    - Global summary of the conversation
    - Recent messages (rolling window of last 10 messages)
    
    Attributes:
        session_id: Unique session identifier
        user_id: User identifier
        global_summary: Summary of the entire conversation
        recent_messages: Last 10 messages (rolling window)
        updated_at: Last update timestamp
    """
    
    session_id: str = Field(..., description="Unique session identifier")
    user_id: str = Field(..., description="User identifier")
    global_summary: str = Field(
        default="",
        description="Summary of the entire conversation"
    )
    recent_messages: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Last 10 messages: [{'role': 'user'|'assistant', 'content': '...'}]"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Last update timestamp"
    )
    
    class Config:
        """Pydantic config."""
        json_schema_extra = {
            "example": {
                "session_id": "sess_abc",
                "user_id": "user_123",
                "global_summary": "User is discussing food preferences and travel plans...",
                "recent_messages": [
                    {"role": "user", "content": "I like pizza"},
                    {"role": "assistant", "content": "Got it! Do you prefer vegetarian?"}
                ],
                "updated_at": "2023-10-27T10:00:00Z"
            }
        }


class MemoryOperation(BaseModel):
    """Represents an operation on memory (used in function calling).
    
    This is the output from LLM's function calling decision process.
    
    Attributes:
        operation: The operation type (ADD, UPDATE, DELETE, NOOP)
        target_memory_id: ID of existing memory to UPDATE or DELETE (None for ADD)
        new_content: New content for ADD or UPDATE
    """
    
    operation: Literal["ADD", "UPDATE", "DELETE", "NOOP"] = Field(
        ...,
        description="Operation type"
    )
    target_memory_id: Optional[str] = Field(
        None,
        description="ID of existing memory to UPDATE or DELETE. Null if ADD."
    )
    new_content: Optional[str] = Field(
        None,
        description="New content for ADD or UPDATE"
    )
    
    class Config:
        """Pydantic config."""
        json_schema_extra = {
            "examples": [
                {
                    "operation": "ADD",
                    "target_memory_id": None,
                    "new_content": "User is vegetarian"
                },
                {
                    "operation": "UPDATE",
                    "target_memory_id": "mem-123",
                    "new_content": "User is vegetarian and prefers organic food"
                },
                {
                    "operation": "DELETE",
                    "target_memory_id": "mem-123",
                    "new_content": None
                },
                {
                    "operation": "NOOP",
                    "target_memory_id": None,
                    "new_content": None
                }
            ]
        }
